# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
osx_image: xcode7.3
cache: cocoapods
podfile: Example/Podfile
before_install:
- gem install cocoapods # Since Travis is not always on latest version
- pod --version
- pod install --project-directory=Example
install:
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet
script:
- set -o pipefail
- xcodebuild test -workspace Example/SwiftFSM.xcworkspace -scheme SwiftFSM-Example -sdk "iphonesimulator9.3" -destination "OS=9.3,name=iPhone 6 Plus" ONLY_ACTIVE_ARCH=NO | xcpretty -c
- xcodebuild build -workspace Example/SwiftFSM.xcworkspace -scheme SwiftFSM-Example -sdk "iphonesimulator9.3" -destination "OS=9.3,name=iPhone 6 Plus" ONLY_ACTIVE_ARCH=NO | xcpretty -c
- pod lib lint --quick
